# Generated by Django 4.1 on 2023-10-10 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('amount', models.FloatField(max_length=19)),
                ('currency', models.CharField(max_length=5)),
                ('txRef', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date_time', models.DateTimeField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('gateway_response', models.CharField(blank=True, max_length=50, null=True)),
                ('transactionComplete', models.BooleanField(default=False)),
                ('course', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
