# Generated by Django 4.1 on 2023-08-07 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='transactionComplete',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='UserPaymentInfo',
        ),
    ]
