# Generated by Django 4.1 on 2023-08-07 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_transactionlog_transactioncomplete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='order_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
