# Generated by Django 4.1 on 2023-08-08 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_rename_status_course_price_status'),
        ('payment', '0004_rename_order_id_transactionlog_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionlog',
            name='course_id',
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course'),
        ),
    ]
