# Generated by Django 4.1 on 2023-08-08 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_rename_status_course_price_status'),
        ('payment', '0005_remove_transactionlog_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='course',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course'),
        ),
    ]
