# Generated by Django 4.1 on 2023-07-31 14:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('Description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='Course_img/%Y/%M')),
                ('price_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'NGN ₦'), ('$', 'USD')], default='NGN', editable=False, max_length=3, null=True)),
                ('price', djmoney.models.fields.MoneyField(blank=True, currency_choices=(('NGN', 'NGN ₦'), ('$', 'USD')), decimal_places=2, default_currency='NGN', max_digits=19, null=True, verbose_name='Price')),
                ('requirement', models.TextField(blank=True, null=True, verbose_name='Requirement')),
                ('discount', models.IntegerField(blank=True, null=True, verbose_name='Discount')),
                ('enroll_fee', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.category')),
            ],
        ),
        migrations.CreateModel(
            name='SubCourse',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Title')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcourse', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review', models.TextField()),
                ('rating', models.IntegerField(verbose_name='Rating')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Is_Locked')),
                ('video', models.FileField(upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])], verbose_name='Video')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duration')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course')),
                ('is_completed', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('subcourse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcourse_lesson', to='courses.subcourse')),
            ],
        ),
    ]
