# Generated by Django 4.1 on 2023-08-01 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_course_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='enroll_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
