# Generated by Django 4.1 on 2023-08-01 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_subscribers'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('requirement', models.TextField(blank=True, null=True, verbose_name='Requirement')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='requirement',
        ),
        migrations.AddField(
            model_name='course',
            name='about_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='courses.aboutcourse'),
        ),
    ]
