# Generated by Django 4.1 on 2023-08-01 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_aboutcourse_remove_course_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='about_course',
        ),
        migrations.AddField(
            model_name='aboutcourse',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_course', to='courses.course'),
        ),
    ]
