# Generated by Django 4.1 on 2023-08-02 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_course_about_course_aboutcourse_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date_created']},
        ),
        migrations.RemoveField(
            model_name='course',
            name='enroll_fee',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price_currency',
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=99999999, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=5), django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Rating'),
        ),
    ]
