# Generated by Django 4.1 on 2023-08-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_review_options_remove_course_enroll_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermidate', 'Intermidate'), ('Advance', 'Advance')], default='Beginner', max_length=15),
        ),
    ]
