# Generated by Django 4.1 on 2023-08-05 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Free', 'Free')], default='Free', max_length=15, null=True),
        ),
    ]
